# Generated by Django 4.2.5 on 2023-09-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
